#ifndef _PKSMCORE_LANG_FOLDER
#define _PKSMCORE_LANG_FOLDER ""
#endif

#ifndef _PKSMCORE_GETLINE_FUNC
#define _PKSMCORE_GETLINE_FUNC getline
#endif

#ifndef _PKSMCORE_DISABLE_THREAD_SAFE_RANDOM
#define _PKSMCORE_DISABLE_THREAD_SAFE_RANDOM
#endif
