#ifndef _PKSMCORE_DISABLE_ABILITY_STRINGS
#define _PKSMCORE_DISABLE_ABILITY_STRINGS
#endif

#ifndef _PKSMCORE_DISABLE_BALL_STRINGS
#define _PKSMCORE_DISABLE_BALL_STRINGS
#endif

#ifndef _PKSMCORE_DISABLE_FORM_STRINGS
#define _PKSMCORE_DISABLE_FORM_STRINGS
#endif

#ifndef _PKSMCORE_DISABLE_HIDDEN_POWER_STRINGS
#define _PKSMCORE_DISABLE_HIDDEN_POWER_STRINGS
#endif

#ifndef _PKSMCORE_DISABLE_ITEM_STRINGS
#define _PKSMCORE_DISABLE_ITEM_STRINGS
#endif

#ifndef _PKSMCORE_DISABLE_MOVE_STRINGS
#define _PKSMCORE_DISABLE_MOVE_STRINGS
#endif

#ifndef _PKSMCORE_DISABLE_NATURE_STRINGS
#define _PKSMCORE_DISABLE_NATURE_STRINGS
#endif

#ifndef _PKSMCORE_DISABLE_GAME_STRINGS
#define _PKSMCORE_DISABLE_GAME_STRINGS
#endif

#ifndef _PKSMCORE_DISABLE_LOCATION_STRINGS
#define _PKSMCORE_DISABLE_LOCATION_STRINGS
#endif

#ifndef _PKSMCORE_DISABLE_GEO_STRINGS
#define _PKSMCORE_DISABLE_GEO_STRINGS
#endif

#ifndef _PKSMCORE_LANG_FOLDER
#define _PKSMCORE_LANG_FOLDER ""
#endif

#ifndef _PKSMCORE_GETLINE_FUNC
#define _PKSMCORE_GETLINE_FUNC getline
#endif

#ifndef _PKSMCORE_DISABLE_THREAD_SAFE_RANDOM
#define _PKSMCORE_DISABLE_THREAD_SAFE_RANDOM
#endif
