name: C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make > build.log
    - name: Upload build log
      uses: actions/upload-artifact@v1
      with:
        name: output.log
        path: build.log
    - name: Upload built file
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: eventspacker
