name: C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macOS-12]
        include:
          - os: ubuntu-22.04
            cc: gcc-11
            cxx: g++-11
            osstring: Linux
          - os: macOS-12
            cc: clang-14
            cxx: clang++-14
            osstring: Darwin

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: make
      run: make CC=${{ matrix.cc }} CXX=${{ matrix.cxx }}
      env:
        OS: ${{ matrix.osstring }}
    - name: Upload built file
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: gallerypack
