name: C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            cc: gcc-9
            cxx: g++-9
            osstring: Linux
          - os: macOS-latest
            cc: clang
            cxx: clang++
            osstring: Darwin

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: make
      run: make CC=${{ matrix.cc }} CXX=${{ matrix.cxx }}
      env:
        OS: ${{ matrix.osstring }}
    - name: Upload built file
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: gallerypack
